name: Deploy Airflow to EC2

on:
    push:
        branches:
            - main

jobs:
    Deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Github Repository Code Load
              uses: actions/checkout@v4

            - name: AWS credentials setting (for Access AWS Resource)
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-region: ap-northeast-2
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

            - name: SSH - EC2 access
              uses: appleboy/ssh-action@v1.0.3
              with:
                  username: ubuntu
                  host: ${{ secrets.EC2_HOST }}
                  key: ${{ secrets.EC2_PRIVATE_KEY }}
                  script_stop: true
                  script: |
                      cd spoton/ || exit 1
                      docker-compose down -v || true
                      sudo rm -rf spoton-airflow/ || true
                      git clone https://github.com/leehah0908/spoton-airflow.git
                      sudo rm -rf .git/ || true
                      sudo rm -rf .github/ || true
                      sudo rm .gitignore/ || true
                      docker-compose up -d
